# Basic Jekyll settings
title: ZoneWeaver API Documentation
description: Documentation for the ZoneWeaver API - Zone Hypervisor Management Backend
baseurl: "" # Keep empty for hosting at the root of the domain
url: "https://makr91.github.io/zoneweaver-api" # GitHub Pages URL
repository: Makr91/zoneweaver-api # for github-metadata

permalink: pretty

# Logo and favicon settings
# logo: "/assets/images/logo.png"
# favicon_ico: "/assets/images/favicon.ico"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.md
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - "*.js"
  - "*.mjs"
  - config/
  - controllers/
  - middleware/
  - models/
  - routes/
  - packaging/
  - scripts/
  - SETUP.md
  - CHANGELOG.md

# Theme settings
theme: just-the-docs

# Theme customization
color_scheme: dark # Or "light", or custom schemes
search_enabled: true # Enable the built-in search

# Aux links for header
aux_links:
  "View on GitHub":
    - "https://github.com/Makr91/zoneweaver-api"
  "ZoneWeaver Frontend":
    - "https://github.com/Makr91/zoneweaver"
aux_links_new_tab: true

# Footer content
footer_content: 'Copyright &copy; 2025 ZoneWeaver Project. Distributed under the GPL-3.0 license.'

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Makr91/zoneweaver-api" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

liquid:
  error_mode: strict
  strict_filters: true

# Navigation structure (can be controlled via front matter in markdown files)
# See Just the Docs documentation for advanced navigation configuration if needed
# https://just-the-docs.com/docs/navigation-structure/

# Markdown processor (kramdown is default and recommended)
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown
  syntax_highlighter: rouge # Use Rouge for syntax highlighting

# Plugins (if using any beyond the theme)
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Enable or disable heading anchors
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

# Enable Mermaid diagrams
mermaid:
  version: "9.1.6"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
