version: 0.0.15
server:
  http_port: 5000
  https_port: 5001
ssl:
  enabled: true
  generate_ssl: true
  key_path: ./ssl/server.key
  cert_path: ./ssl/server.crt
cors:
  whitelist:
    - http://localhost:3000
    - https://localhost:3001
database:
  dialect: sqlite
  storage: ./database.sqlite
  logging: false
api_keys:
  bootstrap_enabled: true
  bootstrap_auto_disable: true
  key_length: 64
  hash_rounds: 12
stats:
  public_access: true
zones:
  discovery_interval: 300
  auto_discovery: true
  max_concurrent_tasks: 5
  task_timeout: 300
  orphan_retention: 7
  default_pagination_limit: 50
provisioning:
  install_tools: false
cleanup:
  interval: 300
vnc:
  web_port_range_start: 8000
  web_port_range_end: 8100
  session_timeout: 1800
  cleanup_interval: 300
  bind_address: 127.0.0.1
  max_concurrent_sessions: 10
host_monitoring:
  enabled: true
  auto_enable_network_accounting: true
  network_accounting_file: /var/log/net.log
  intervals:
    network_config: 60
    network_stats: 10
    network_usage: 10
    storage: 300
    storage_frequent: 10
    device_discovery: 60
    system_metrics: 30
  retention:
    network_stats: 7
    network_usage: 30
    network_config: 90
    storage: 90
    cpu_stats: 7
    memory_stats: 7
  error_handling:
    max_consecutive_errors: 5
    retry_delay: 30
    reset_error_count_after: 3600
  performance:
    max_concurrent_scans: 3
    command_timeout: 30
    batch_size: 100
reconciliation:
  enabled: true
  interval: 3600
  log_level: info
